# TODO: come back to this and get it to install docker and move the image to correct folder

#version: 0.0
#os: linux
#files:
# TODO: move docker image to /apps folder
# TODO: remember this is amazon linux and it uses yum or some shit (google)
#  - source: package.json
#    destination: /apps/test-node-deploy
#  - source: node_modules
#    destination: /apps/test-node-deploy/node_modules/
#  - source: views
#    destination: /apps/test-node-deploy/views
#  - source: app.js
#    destination: /apps/test-node-deploy
#  - source: scripts/test-node-deploy-server.conf
#    destination: /etc/supervisor/conf.d/

#permissions:
#  - object: /
#    pattern: "**"
#    owner: cameronrl
#    group: test-node-deloy-apps

#hooks:
#  BeforeInstall:
# TODO: install docker
#    - location: scripts/clean-deps.sh
#      runas: root
#  AfterInstall:
#    - location: scripts/install-deps.sh
#      runas: root
#  ApplicationStart:
# TODO: run docker image
#    - location: scripts/start.sh
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop.sh
#      runas: root

