version: 2.0

jobs:
  build:
    working_directory: /src
    docker:
      - image: cameronrll/node-docker-example:0.0.2
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "package.json" }}
      - run:
          name: Mocha tests
          command: ./node_modules/.bin/mocha
      - save_cache:
          key: deps-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

#  deploy:
#    working_directory: /src
#    docker:
#      - image: cameronrll/node-docker-example:0.0.2
  deploy:
    machine:
      enabled: true
    working_directory: ~/circleci
    steps:
      - checkout
#      - run:
#          name: Docker build
#          command: docker build -t="node-example-build" .
#      - run:
#          name: Docker images
#          command: docker images
#      - run:
#          name: pwd
#          command: pwd
#      - run:
#          name: ls
#          command: ls
#      - run:
#          name: ls root
#          command: ls ~
#      - run:
#          name: ls above root
#          command: ls ~/../..
#      - run:
#          name: ls docker images
#          command: ls ~/../../var/lib/docker
      # TODO: build docker file into an image here!
      # TODO: then put in a folder
      # TODO: push only that folder to s3
      - run:
          name: Deploy script
          command: ./scripts/deploy_dev.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build