version: 2.0

jobs:
  build:
    working_directory: /src
    docker:
      - image: cameronrll/node-docker-example:0.0.2
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "package.json" }}
      - run:
          name: Mocha tests
          command: ./node_modules/.bin/mocha
      - save_cache:
          key: deps-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  deploy_master:
    machine:
      enabled: true
    working_directory: ~/circleci
    steps:
      - checkout
      - run:
          name: Deploy script
          command: ./scripts/deploy_master.sh

  deploy_dev:
    machine:
      enabled: true
    working_directory: ~/circleci
    steps:
      - checkout
      - run:
          name: Deploy script
          command: ./scripts/deploy_dev.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy_master:
          filters:
            branches:
              only:
                - master
          requires:
            - hold
      - deploy_dev:
          filters:
            branches:
              only:
                - dev
          requires:
            - build