version: 2.0

jobs:
  test:
    working_directory: /src
    docker:
      - image: cameronrll/node-docker-example:0.0.1
    steps:
      - checkout
      - restore_cache:
        key: deps-cache-{{ checksum "package.json" }}
      - run:
        name: Mocha tests
        command: ./node_modules/.bin/mocha
      - save_cache:
        key: deps-cache-{{ checksum "package.json" }}
        paths:
          - node_modules

  deploy:
    working_directory: /src
    docker:
      - image: cameronrll/node-docker-example:0.0.1
    steps:
      - checkout
      - restore_cache:
        key: deps-cache-{{ checksum "package.json" }}
      - run:
        name: Deploy script
        command: ./scripts/deploy_dev.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
        requires:
          - test